spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jongwong}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: WARN
    com.jongwong: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
