import dedent from 'dedent'

import { es } from '@open-pencil/emit'

export const STORYBOOK_FRAMEWORKS = ['react', 'vue', 'html'] as const
export type StorybookFramework = (typeof STORYBOOK_FRAMEWORKS)[number]

/** Tells readers the file is generated; nothing parses it. */
const HEADER = '// Generated by OpenPencil. Re-export to update; edits are overwritten.'

/**
 * How a variant property is controlled. A boolean value's property becomes a boolean arg that
 * picks its on or off variant; the interaction-state property is left to each story, with a
 * `disabled` arg picking its disabled variant when the set draws one.
 */
export type StoryControl =
  | { type: 'boolean'; name: string; on: string; off: string }
  | { type: 'state'; rest: string; disabled?: string }

export interface StoryProp {
  name: string
  options: string[]
  control?: StoryControl
}

/** Everything a story module varies by; the TypeScript around it is a fixed template. */
export interface StoryModuleData {
  framework: StorybookFramework
  title: string
  /** Group name used in the missing-variant error. */
  name: string
  props: StoryProp[]
  variants: { values: string[]; html: string }[]
  metaDesign: StoryDesign[]
  /** Import path of each design image, by variant index. */
  images: string[]
  stories: { exportName: string; label: string; values: string[]; design: StoryDesign[] }[]
}

export type StoryDesign =
  | { type: 'link'; url: string }
  /** Refers to the design image of the variant with this index. */
  | { type: 'image'; variant: number }

const MODULE = es.parseModule(dedent`
  import type { Meta, StoryObj } from '$storybook'

  type Args = $Args

  const variants: Record<string, string> = $variants

  function variantHTML(args: Args): string {
    const key = JSON.stringify($key)
    const html = variants[key]
    if (html === undefined) throw new Error($missing + key)
    return html
  }

  const meta = {
    title: $title,
    parameters: $parameters,
    args: $args,
    argTypes: $argTypes,
    render: (args) => $render
  } satisfies Meta<Args>

  export default meta
  type Story = StoryObj<Args>
`)

const IMAGE = es.parseModule(`const $name = new URL($path, import.meta.url).href`)
const STORY = es.parseModule(`export const $name: Story = $story`)

const FRAMEWORKS: Record<
  StorybookFramework,
  { storybook: string; imports: es.SyntaxNode[]; render: es.SyntaxNode }
> = {
  react: {
    storybook: '@storybook/react-vite',
    imports: es.parseModule(`import { createElement } from 'react'`).body,
    render: es.parseExpression(
      `createElement('div', { dangerouslySetInnerHTML: { __html: variantHTML(args) } })`
    )
  },
  vue: {
    storybook: '@storybook/vue3-vite',
    imports: es.parseModule(`import { h } from 'vue'`).body,
    render: es.parseExpression(`{ setup: () => () => h('div', { innerHTML: variantHTML(args) }) }`)
  },
  html: {
    storybook: '@storybook/html-vite',
    imports: [],
    render: es.parseExpression('variantHTML(args)')
  }
}

const imageName = (variant: number) => `design${variant}`

const BOOLEAN = es.parseType('boolean')
const CONDITION = es.parseExpression('$test ? $then : $else')
const boolean = (value: boolean) => es.parseExpression(String(value))

function argRef(name: string): es.SyntaxNode {
  return {
    type: 'MemberExpression',
    object: es.identifier('args'),
    property: es.string(name),
    computed: true,
    optional: false
  }
}

/** The `disabled` arg a state property adds, unless a boolean value already takes the name. */
function disabledArg(data: StoryModuleData): { property: string; value: string } | null {
  if (
    data.props.some((prop) => prop.control?.type === 'boolean' && prop.control.name === 'disabled')
  )
    return null
  for (const prop of data.props)
    if (prop.control?.type === 'state' && prop.control.disabled !== undefined)
      return { property: prop.name, value: prop.control.disabled }
  return null
}

/** The arg a prop is set by: a boolean prop's own name, otherwise the property's. */
const argName = (prop: StoryProp) =>
  prop.control?.type === 'boolean' ? prop.control.name : prop.name

/** The variant value a prop shows, as an expression over `args`. */
function propValue(data: StoryModuleData, prop: StoryProp): es.SyntaxNode {
  const control = prop.control
  if (control?.type === 'boolean')
    return es.fill(CONDITION, {
      $test: argRef(control.name),
      $then: es.string(control.on),
      $else: es.string(control.off)
    })
  const disabled = disabledArg(data)
  if (disabled?.property === prop.name)
    return es.fill(CONDITION, {
      $test: argRef('disabled'),
      $then: es.string(disabled.value),
      $else: argRef(prop.name)
    })
  return argRef(prop.name)
}

function argsObject(data: StoryModuleData, values: string[]): es.SyntaxNode {
  const entries = data.props.map((prop, i): [string, es.SyntaxNode] => {
    const value = values[i] ?? ''
    if (prop.control?.type === 'boolean')
      return [prop.control.name, boolean(value === prop.control.on)]
    // A disabled story says so through `disabled`, so clearing it shows the rest state.
    if (prop.control?.type === 'state' && value === disabledArg(data)?.value)
      return [prop.name, es.string(prop.control.rest)]
    return [prop.name, es.string(value)]
  })
  const disabled = disabledArg(data)
  if (disabled) {
    const index = data.props.findIndex((prop) => prop.name === disabled.property)
    entries.push(['disabled', boolean(values[index] === disabled.value)])
  }
  return es.object(entries)
}

function argTypes(data: StoryModuleData): es.SyntaxNode {
  const entries = data.props.map((prop): [string, es.SyntaxNode] => {
    if (prop.control?.type === 'boolean')
      return [prop.control.name, es.object([['control', es.string('boolean')]])]
    if (prop.control?.type === 'state')
      return [prop.name, es.object([['table', es.object([['disable', boolean(true)]])]])]
    return [
      prop.name,
      es.object([
        ['control', es.string('select')],
        ['options', es.array(prop.options.map(es.string))]
      ])
    ]
  })
  if (disabledArg(data)) entries.push(['disabled', es.object([['control', es.string('boolean')]])])
  return es.object(entries)
}

function parameters(design: StoryDesign[]): es.SyntaxNode {
  const entries = design.map((entry) =>
    entry.type === 'link'
      ? es.object([
          ['name', es.string('OpenPencil')],
          ['type', es.string('link')],
          ['url', es.string(entry.url)]
        ])
      : es.object([
          ['name', es.string('Design')],
          ['type', es.string('image')],
          ['url', es.identifier(imageName(entry.variant))]
        ])
  )
  return es.object([['design', es.array(entries)]])
}

const NO_ARGS = es.parseType('Record<string, never>')

function argsType(data: StoryModuleData): es.SyntaxNode {
  if (data.props.length === 0) return NO_ARGS
  const entries = data.props.map((prop): [string, es.SyntaxNode] => [
    argName(prop),
    prop.control?.type === 'boolean' ? BOOLEAN : es.stringUnionType(prop.options)
  ])
  if (disabledArg(data)) entries.push(['disabled', BOOLEAN])
  return es.objectType(entries)
}

/** Print a CSF3 story module for one component or component set. */
export function printStoryModule(data: StoryModuleData): string {
  const framework = FRAMEWORKS[data.framework]
  const [storybookImport, ...body] = es.fill(MODULE, {
    $storybook: es.string(framework.storybook),
    $Args: argsType(data),
    $variants: es.object(
      data.variants.map((variant) => [JSON.stringify(variant.values), es.string(variant.html)])
    ),
    $key: es.array(data.props.map((prop) => propValue(data, prop))),
    $missing: es.string(`${data.name} has no variant `),
    $title: es.string(data.title),
    $parameters: data.metaDesign.length > 0 ? parameters(data.metaDesign) : es.OMIT,
    $args: argsObject(data, data.variants[0]?.values ?? []),
    $argTypes: argTypes(data),
    $render: framework.render
  }).body
  const images = data.images.flatMap(
    (path, i) =>
      es.fill(IMAGE, { $name: es.identifier(imageName(i)), $path: es.string(`./${path}`) }).body
  )
  const stories = data.stories.flatMap(
    (story) =>
      es.fill(STORY, {
        $name: es.identifier(story.exportName),
        $story: es.object([
          ['name', es.string(story.label)],
          ...(story.design.length > 0 ? [['parameters', parameters(story.design)] as const] : []),
          ['args', argsObject(data, story.values)]
        ])
      }).body
  )
  const module = es.printModule({
    type: 'Program',
    sourceType: 'module',
    body: [storybookImport, ...framework.imports, ...images, ...body, ...stories]
  })
  return `${HEADER}\n${module}\n`
}
